canonical/vault-rock

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
.github/workflows/build-rock.yaml
.github/workflows/integration-tests.yaml
.github/workflows/main.yaml
.github/workflows/publish-rock.yaml
.github/workflows/scan-rock.yaml
CODEOWNERS
CONTRIBUTING.md
README.md
renovate.json
rockcraft.yaml
tests/config/config.hcl
tests/pyproject.toml
tests/requirements.txt
tests/test_integration.py
tests/tox.ini
tests/vault.py

This PR implements the first version of the ROCK for Vault. It includes the following content:
- The actual ROCK
- The CI for testing it and publishing it that contains
- Build
- Integration tests
- Security scanning
- Publishing
For now this ROCK is quite larger than the upstream version. Follow up PR's should aim at reducing the ROCK size (leveraging the bare base and chisel)
```console
guillaume@potiron:~/PycharmProjects/vault-rock$ docker images
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
vault        1.14.3    e17cf1b74b17   11 hours ago   448MB
vault        1.13.3    e66677b2b1b7   6 weeks ago    255MB
```

[Feat] Creates ROCK for Vault

---

CONTRIBUTING.md
README.md

The goal here is to make our life easier when needing to update the Vault version. Now we only have to update 1 file when that's the case (`rockcraft.yaml`)

[chore] Removes version from contributing.md

---

.github/workflows/publish-rock.yaml
README.md

Publishes image with "latest" tag in addition to rock version.

[feat] Publishes image with "latest" tag in addition to rock version

---

rockcraft.yaml

[feat] Bumps Vault version to 1.15.0

---

rockcraft.yaml

feat: Bumps to v1.15.1

---

rockcraft.yaml

Adds support for arm. There is no CI infrastructure yet to build the ROCK for arm, to come in the future.

feat: Adds support for arm

---

rockcraft.yaml

feat: Bumps vault version to 1.15.2

---

rockcraft.yaml

Bumps to using the latest Vault release: 1.15.4.

chore: Bumps to v1.15.4

---

rockcraft.yaml

chore: Bump Vault to v1.15.5

---

rockcraft.yaml

chore: bump vault to v.1.15.6

---

rockcraft.yaml

Bump to v1.16.0
Please do not merge until the following actions are completed:
- #32 is merged
- A new `release-1.15` branch is created
- A branch protection rule is created for `release-*`

chore: bump to v1.16.0

---

rockcraft.yaml

chore: bump vault to v1.16.1

---

.github/ISSUE_TEMPLATE/bug_report.yml

Replace any charm specific content with rock in the issue form.

chore: removes charm content in issue form

---

rockcraft.yaml

chore: bump vault to 1.16.2

---

rockcraft.yaml

chore: bump vault to 1.17.0

---

rockcraft.yaml

bump vault to 1.17.2
https://github.com/hashicorp/vault/releases/tag/v1.17.2

chore: bump vault to 1.17.2

---

rockcraft.yaml

chore: bump vault to v1.17.3

---

rockcraft.yaml

chore: bump vault to v1.17.5

---

rockcraft.yaml

chore: bump vault to v1.17.6

---

README.md
rockcraft.yaml

Here we bump the Vault version to the latest from the upstream.
Prior to merging this PR we also need to create a git branch for 1.17.

chore: bump vault to 1.18.3

---

rockcraft.yaml

Here we bump workload to v1.19.0, which is a `minor` release. Which means we need to do the following prior to merging this PR:

chore: bump workload to v1.19.0

---

rockcraft.yaml

chore: bump vault to v1.19.3
